# Generated by Django 5.0.3 on 2024-03-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default='default_video.jpg', upload_to='images/'),
        ),
    ]
